spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reco
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
    port: 3001

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:5173/oauth/kakao/callback

google:
  client-id: ${GOOGLE_CLIENT_ID}
  redirect-uri: http://localhost:5173/oauth/google/callback

